"""Apify YouTube Source — cloud video + transcript scraping.

Why this exists: the default `youtube.py` path uses youtube-transcript-api, which
gets the *server's* IP blocked when it runs in the cloud (Render etc.) — that is
the whole reason the project shipped with a local Mac scraper. Apify runs the
discovery + transcript fetch on its own infrastructure, so the backend can pull
transcripts reliably from anywhere without a machine sitting at home.

It calls Apify's `run-sync-get-dataset-items` endpoint, which starts the actor,
waits for it to finish, and returns the scraped dataset in one request.

Output field names differ between actors, so parsing here is intentionally
defensive. Override the actor with APIFY_YOUTUBE_ACTOR, or supply a full input
payload with APIFY_YOUTUBE_INPUT, without touching this file.
"""
import json
from datetime import datetime
from typing import AsyncIterator
from urllib.parse import quote_plus

import httpx

from config import (
    APIFY_API_TOKEN,
    APIFY_YOUTUBE_ACTOR,
    APIFY_MAX_RESULTS_PER_QUERY,
    APIFY_YOUTUBE_INPUT,
    YOUTUBE_CHANNELS,
    YOUTUBE_SEARCH_TERMS,
)
from .base import BaseSource, ContentItem


class ApifyYouTubeSource(BaseSource):
    """Fetch YouTube videos + transcripts via an Apify actor."""

    name = "youtube"
    base_url = "https://api.apify.com/v2"

    def __init__(self):
        self.token = APIFY_API_TOKEN
        self.actor = APIFY_YOUTUBE_ACTOR

    async def is_configured(self) -> bool:
        return bool(self.token)

    async def fetch(self, limit: int = 50) -> AsyncIterator[ContentItem]:
        if not await self.is_configured():
            print("Apify not configured (APIFY_API_TOKEN missing), skipping")
            return

        run_input = self._build_input()
        try:
            items = await self._run_actor(run_input)
        except Exception as e:
            print(f"Apify run failed: {e}")
            return

        count = 0
        seen: set[str] = set()
        for raw in items:
            try:
                item = self._parse_item(raw)
            except Exception as e:
                print(f"Apify item parse error: {e}")
                continue
            if not item or item.source_id in seen:
                continue
            seen.add(item.source_id)
            yield item
            count += 1
            if count >= limit:
                break

    def _build_input(self) -> dict:
        """Build the actor input. Channel + search pages go in as startUrls so we
        don't depend on a particular actor's bespoke search-field name."""
        if APIFY_YOUTUBE_INPUT:
            try:
                return json.loads(APIFY_YOUTUBE_INPUT)
            except json.JSONDecodeError:
                print("APIFY_YOUTUBE_INPUT is not valid JSON, falling back to default input")

        start_urls = []
        for channel_id in YOUTUBE_CHANNELS:
            start_urls.append({"url": f"https://www.youtube.com/channel/{channel_id}/videos"})
        for term in YOUTUBE_SEARCH_TERMS[:8]:
            start_urls.append({"url": f"https://www.youtube.com/results?search_query={quote_plus(term)}"})

        return {
            "startUrls": start_urls,
            "maxResults": APIFY_MAX_RESULTS_PER_QUERY,
            "maxResultsShorts": 0,
            "maxResultStreams": 0,
            "downloadSubtitles": True,
            "saveSubsToKVS": False,
            "subtitlesLanguage": "en",
            "subtitlesFormat": "plaintext",
            "preferAutoGeneratedSubtitles": True,
        }

    async def _run_actor(self, run_input: dict) -> list[dict]:
        """Run the actor synchronously and return its dataset items."""
        url = f"{self.base_url}/acts/{self.actor}/run-sync-get-dataset-items"
        params = {"token": self.token, "clean": "true"}
        # Actor runs can take a while; give them room but don't hang forever.
        async with httpx.AsyncClient(timeout=300.0) as client:
            response = await client.post(url, params=params, json=run_input)
            if response.status_code >= 400:
                raise RuntimeError(f"Apify HTTP {response.status_code}: {response.text[:300]}")
            data = response.json()
        # Endpoint returns a bare list of dataset items.
        if isinstance(data, dict):
            data = data.get("items", data.get("data", []))
        return data if isinstance(data, list) else []

    def _parse_item(self, raw: dict) -> ContentItem | None:
        video_id = (
            raw.get("id")
            or raw.get("videoId")
            or self._id_from_url(raw.get("url") or raw.get("videoUrl") or "")
        )
        if not video_id:
            return None

        title = raw.get("title") or raw.get("name") or ""
        url = raw.get("url") or raw.get("videoUrl") or f"https://www.youtube.com/watch?v={video_id}"
        author = raw.get("channelName") or raw.get("channelTitle") or raw.get("author") or ""

        transcript = self._extract_transcript(raw)
        description = raw.get("text") or raw.get("description") or ""
        content = transcript or description or title
        content = content[:5000]

        return ContentItem(
            source="youtube",
            source_id=str(video_id),
            title=title,
            content=content,
            url=url,
            author=author,
            engagement=self._as_int(raw.get("viewCount") or raw.get("views")),
            published_at=self._parse_date(raw.get("date") or raw.get("publishedAt") or raw.get("uploadDate")),
            metadata={
                "likes": self._as_int(raw.get("likes") or raw.get("likeCount")),
                "comments": self._as_int(raw.get("commentsCount") or raw.get("commentCount")),
                "channel_id": raw.get("channelId") or raw.get("channelUrl") or "",
                "has_transcript": bool(transcript),
                "via": "apify",
            },
        )

    @staticmethod
    def _extract_transcript(raw: dict) -> str:
        """Pull transcript text out of whatever shape the actor returned.

        The default streamers/youtube-scraper actor returns `subtitles` as a list
        of language *tracks*, each carrying the full transcript in a `plaintext`
        field. Other actors return a list of caption *segments* ({text}/{line}) or
        a bare string. Handle all three: for full tracks we pick one (preferring
        English) instead of concatenating duplicate languages; for segments we
        join them in order.
        """
        for key in ("transcript", "subtitles", "captions", "subtitle"):
            value = raw.get(key)
            if not value:
                continue
            if isinstance(value, str):
                return value
            if isinstance(value, dict):
                text = value.get("plaintext") or value.get("text")
                if isinstance(text, str) and text.strip():
                    return " ".join(text.split())
                continue
            if isinstance(value, list):
                # Case 1: list of full language tracks (each has `plaintext`).
                tracks = [
                    s for s in value
                    if isinstance(s, dict) and isinstance(s.get("plaintext"), str) and s["plaintext"].strip()
                ]
                if tracks:
                    english = [t for t in tracks if str(t.get("language", "")).lower().startswith("en")]
                    best = max(english or tracks, key=lambda t: len(t["plaintext"]))
                    return " ".join(best["plaintext"].split())
                # Case 2: list of caption segments or raw strings -> concatenate.
                parts: list[str] = []
                for seg in value:
                    if isinstance(seg, str):
                        parts.append(seg)
                    elif isinstance(seg, dict):
                        text = seg.get("text") or seg.get("line") or seg.get("content")
                        if text:
                            parts.append(text)
                        elif isinstance(seg.get("subtitles"), str):
                            parts.append(seg["subtitles"])
                if parts:
                    return " ".join(parts)
            if isinstance(value, dict) and isinstance(value.get("text"), str):
                return value["text"]
        return ""

    @staticmethod
    def _id_from_url(url: str) -> str:
        if "watch?v=" in url:
            return url.split("watch?v=")[1].split("&")[0]
        if "youtu.be/" in url:
            return url.split("youtu.be/")[1].split("?")[0]
        return ""

    @staticmethod
    def _as_int(value) -> int:
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return 0

    @staticmethod
    def _parse_date(value) -> datetime:
        if not value:
            return datetime.utcnow()
        try:
            return datetime.fromisoformat(str(value).replace("Z", "+00:00")).replace(tzinfo=None)
        except (ValueError, AttributeError):
            return datetime.utcnow()
